### PR TITLE
Update README.md Fixes #132

### LINKED ISSUE #132: No License
I'm just figuring out that there's no ofxImGui license at all.
As ImGui is MIT, let's add a MIT license to this addon for clarity ?

Ping @prisonerjohn , @jvcleave .

### PR DESCRIPTION
**Pull request by GitBruno**
Refer/link to local original MIT licence

### CODE REVIEW

**Comment by GitBruno** [comment]
Just realise you might want to have this PR on the Develop branch. When are you planning to merge Develop into Master?

**Comment by Daandelange** [comment]
Thanks for the PR. Yes, but we can add it to both branches. ;)  
(`master` will be renamed `legacy`, `develop` will become `main` (or `master`).

`develop` : I hoped to merge it about a year ago, without success, I want the merge to be "clean". The feedback period has confirmed that common platforms & default compilation settings work well, many people already use the develop branch. Extended platform support will solve itself over time as people use it. As to the compilation options and documentation, I've started a cleaning-up-rush recently (thus the license issue too) and I'm close to having more time to clean up & test the latest things to finally get this merged ^_^ .

**Comment by Daandelange** [comment]
Adding the License.md file would be needed too.

**Comment by GitBruno** [comment]
You're right! I feel like that is something you need to do as that one will require your name.

**Comment by Daandelange** [comment]
Ok, then I'll include this in my cleaning-up list, thanks for trying to help anyways. ;)

**Pull request closed without merging**
