### PR TITLE
Set default flag in imgui_internal.h

### PR DESCRIPTION
**Pull request by GitBruno**
Set default to 0 (ImGuiItemFlags_None)

consistent with other defaults

### CODE REVIEW

**Comment by Daandelange** [comment]
Hi, thanks for your PR but I'm not keen of introducing custom changes to [the original imgui files](https://github.com/ocornut/imgui/blob/a8e96ae21a4ec10e5f02b19dd865dfffe8a98e67/imgui_internal.h#L3144); maybe this is rather an ImGui API inconsistency ? Otherwise, as this change doesn't break any API, I could accept the change but it will need to be integrated in [the automatic update script](https://github.com/jvcleave/ofxImGui/blob/develop/Developpers.md#updating-imgui) to make it persistent in ofxImGui, as I have done with some necessary changes for OF compatibility.

**Comment by GitBruno** [comment]
I added a pull request at source. There where some other issues as well. See [0d3cf29](https://github.com/jvcleave/ofxImGui/pull/127/commits/0d3cf29486fa9c0d81ee28a2c6aaf08f6d559abf) and [b1ba163](https://github.com/jvcleave/ofxImGui/pull/127/commits/b1ba163affa74bc7d917fe931a0245c8340658ac)

**Comment by Daandelange** [comment]
Hi, sorry for the delay, I'll still keep these 2 last commits (so reopening this pr).
If I understood it correctly, [the `imgui_internal.h` merge will not happen in imgui](https://github.com/ocornut/imgui/pull/7784), right ?

**Comment by GitBruno** [comment]
That is correct so I agree with you we should not do this here.

**Comment by Daandelange** [comment]
Ok :)
Btw, I just cherry-picked these 2 later commits ;)

**Pull request closed without merging**
