### PR TITLE
Update to dear ImGui 1.62

### PR DESCRIPTION
**Pull request by s-ol**
version 1.53 also included for compatibility.

### CODE REVIEW

**Comment by prisonerjohn** [comment]
Thanks for this. I've already started some of this work on the `develop` branch though. Do you think you could merge against that instead?

**Comment by s-ol** [comment]
ah yeah, i had realized only when pushing that that branch even exists. I will see if it needs a rebase or just changing the base of the PR.

**Comment by s-ol** [comment]
@prisonerjohn any news?

**Comment by prisonerjohn** [comment]
Thanks for the reminder, just merged it in and had to add a fix to the Helpers.

**Pull request merged**
