### PR TITLE
Add vulkan render engine

### PR DESCRIPTION
**Pull request by tgfrerer**
* Adds a vk engine which renders ofxImGui using the openFrameworks vulkan renderer. The headers for the new engine are excluded from GLES/GL builds, which should continue working as-is.

More on the oF vulkan renderer [in the oF forum](https://forum.openframeworks.cc/t/vulkan-renderer/23800)

For an example app using the oF vulkan renderer with ofxImGui, see [here](https://github.com/openframeworks-vk/openFrameworks/tree/vk/apps/devApps/testVkImGui). 

* Also adds an oF logger channel to ofxImgui, which allows the openFrameworks log to be re-routed to imgui, and thus the screen.

### CODE REVIEW

**Comment by prisonerjohn** [comment]
Thanks @tgfrerer this looks great. Is there a particular reason why you put the `LoggerChannel` in the same file as the `Helpers`? I'm thinking it might be a good idea to split these up.

**Comment by tgfrerer** [comment]
Hey @prisonerjohn - I put it in there for it seemed the most fitting files - but no problem extracting it into its own two files, if you prefer.

**Comment by tgfrerer** [comment]
I've extracted the loggerchannel logic into it's own file. I've not named it more generically, i.e. "LoggerChannel" because oF has a tendency to include all files inside an addon/src into the global include search paths, and a name like "LoggerChannel" might clash with / or be already taken by another flavour of logger channel.

**Comment by jvcleave** [comment]
I've created a release version prior to this merge in case there are issues with untested platforms.

**Comment by prisonerjohn** [comment]
How do you feel about including the shaders in the `EngineVk.cpp` file? Right now, they're not included in the addon, only in the example in the of-vk repo. I don't think these will need to be modified by user, so it might make sense to just have them directly in the file.

**Comment by tgfrerer** [comment]
good point! I'll send a PR once i get to it.

**Pull request merged**
