### PR TITLE
Allow multiple instances of ImGui

### PR DESCRIPTION
**Pull request by jordiexvision**
Added some fixes to allow multiple instances of ImGui in the same application. For example, when opening several instances of the same application in different windows.
The current code works for me, but not sure if I'm breaking things here. 
Please check.

Thank you for the addon!

https://github.com/ocornut/imgui/issues/586

### CODE REVIEW

**Comment by moebiussurfing** [comment]
hey @jordiexvision , this is working now?
I am looking for the same thing, to use more than one instance in some classes...

**Comment by moebiussurfing** [comment]
hey @jordiexvision, just in case you still needing this:
I got it work with this branch:
https://github.com/jvcleave/ofxImGui/pull/91

**Comment by moebiussurfing** [comment]
> 
> 
> Added some fixes to allow multiple instances of ImGui in the same application. For example, when opening several instances of the same application in different windows.
> The current code works for me, but not sure if I'm breaking things here.
> Please check.
> 
> Thank you for the addon!
> 
> [ocornut/imgui#586](https://github.com/ocornut/imgui/issues/586)

hey @jordiexvision ,
are you using this updates into the up to date repo?
I am having crashes on exit when using more than one instance.
I think this is really helpful

**Comment by shoxter** [comment]
Any updates on this? I really need to use multiple instances of Imgui in my project.

I don't want to have to incorporate Nuklear into my project but that seems to be my only other option if I can't get multiple Imgui instances working.

**Comment by Daandelange** [comment]
I'm closing this PR as it's been supported in the develop branch for a while. ;)

**Pull request closed without merging**
